### ISSUE TITLE
One Light returns to previous state

### ISSUE THREAD

**Issue by mdeweerd** [TheHolyRoger/THR_HA_Blueprints#1]
Hi

I tested the moes_scene_switch_multi_press.yaml blueprint with zigbee light and I get an on command followed by a off command immediately (or vice versa) - so the light returns to the initial state.

I guess you're more familiar with the blueprint so you might spot the reason immediately.  This does not happen with a simple on/off command.
[trace automation.exterieur_3_button 2023-10-16T20_20_57.606094+00_00.json](https://github.com/TheHolyRoger/THR_HA_Blueprints/files/12921618/trace.automation.exterieur_3_button.2023-10-16T20_20_57.606094%2B00_00.json)

This is the trace for the configuration further below.

Configuration:

```yaml
id: '1697486579369'
alias: Exterieur-3-button
description: Lampe Exterieur 3 boutons (miliue)
use_blueprint:
  path: TheHolyRoger/moes_scene_switch_multi_press.yaml
  input:
    controller_device: c831e7fdf18d22b927bf0f3ef9703186
    button_endpoint_id: 2
    helper_last_controller_event: input_text.last_state_3button_2
    controlled_light_entity: light.tz3000_utagpnzs_ts0505a_level_light_color_on_off
    button_multi_press_enabled: true
    button_toggle_controlled_light_entity_first_press: true
```
